[package]
name = "mio-abstract-path"
version = "0.1.0"
edition = "2021"

[dependencies]
mio = { version = "=1.0.0", features = ["net"] }

# Works with:
# mio = { version = "=0.8.11", features = ["net", "os-poll"] }
